#ifndef NEXUSMINER_GPU_CUDA_SIEVE_SMALL_PRIME_CONSTANTS_CUH
#define NEXUSMINER_GPU_CUDA_SIEVE_SMALL_PRIME_CONSTANTS_CUH

//magic number bit masks used by the small prime sieve.  Generate these using print_code function in small_sieve_tools.cpp
//using device (global) memory is significantly faster than putting these in constant memory.  Todo - try texture memory
#include <stdint.h>
namespace nexusminer {
	namespace gpu {

__device__ const uint32_t p7[7] =         {0x7eefdffd, 0xfdbffbf7, 0xf77eefdf, 0xdffdbffb,
                                             0xfbf77eef, 0xefdffdbf, 0xbffbf77e};

__device__ const uint32_t p11[11] =       {0xffeffffb, 0xdffff7ff, 0x7dffbeff, 0xeffffbdf,
                                             0xfff7ff7d, 0xffbeffef, 0xfffbdfff, 0xf7ff7dff,
                                             0xbeffefff, 0xfbdffff7, 0xff7dffbe};

__device__ const uint32_t p13[13] =       {0xfefffff7, 0xf7efffff, 0xff7ffdfb, 0xfbffdfbf,
                                             0xbffeffff, 0xfff7efff, 0xffff7ffd, 0xfdfbffdf,
                                             0xdfbffeff, 0xfffff7ef, 0xefffff7f, 0x7ffdfbff,
                                             0xffdfbffe};

__device__ const uint32_t p17[17] =       {0x7fffffef, 0xfbfdffff, 0xffbfdfff, 0xfffffeff,
                                             0xffffeff7, 0xfdffff7f, 0xbfdffffb, 0xfffeffff,
                                             0xffeff7ff, 0xffff7fff, 0xdffffbfd, 0xfeffffbf,
                                             0xeff7ffff, 0xff7fffff, 0xfffbfdff, 0xffffbfdf,
                                             0xf7fffffe};

__device__ const uint32_t p19[19] =       {0xffffffdf, 0xbffffdff, 0xffffffef, 0xfff7ffff,
                                             0xfeffbfff, 0xdffbffff, 0xff7ffff7, 0xeffffeff,
                                             0xffffdffb, 0xfffdff7f, 0xffffefff, 0xf7ffffff,
                                             0xffbffffd, 0xfbffffff, 0x7ffff7ff, 0xfffeffbf,
                                             0xffdffbff, 0xfdff7fff, 0xffeffffe};

__device__ const uint32_t p23[23] =       {0xffffffbf, 0xfeffffff, 0xbffdffff, 0xff7ff7ff,
                                             0xffffffdf, 0xfffffbff, 0xdfffffef, 0xffffffff,
                                             0xeffeffff, 0xffbffdff, 0xffff7ff7, 0xffffffff,
                                             0xf7fffffb, 0xffdfffff, 0xfbffffff, 0xffeffeff,
                                             0xffffbffd, 0xffffff7f, 0xfdffffff, 0x7ff7ffff,
                                             0xffffdfff, 0xfffbffff, 0xffffeffe};

__device__ const uint32_t p29[29] =       {0xffffff7f, 0xffffffff, 0xffffffff, 0xbfffffff,
                                             0xffbfffff, 0xffffbfff, 0xffffffbf, 0xdfffffff,
                                             0xffdfffff, 0xefffdfff, 0xffefffdf, 0xffffefff,
                                             0xffffffef, 0xf7ffffff, 0xfff7ffff, 0xfbfff7ff,
                                             0xfffbfff7, 0xfffffbff, 0xfffffffb, 0xfdffffff,
                                             0xfffdffff, 0xfffffdff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xfeffffff, 0x7ffeffff, 0xff7ffeff,
                                             0xffff7ffe};

__device__ const uint32_t p31[31] =       {0xfffffeff, 0xfffeffff, 0xfeffff7f, 0xffff7fff,
                                             0xff7fffff, 0x7fffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffbfff, 0xffbfffff, 0xbfffffff,
                                             0xffffffdf, 0xffffdfff, 0xffdfffef, 0xdfffefff,
                                             0xffefffff, 0xefffffff, 0xfffffff7, 0xfffff7ff,
                                             0xfff7fffb, 0xf7fffbff, 0xfffbffff, 0xfbffffff,
                                             0xfffffffd, 0xfffffdff, 0xfffdffff, 0xfdffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p37[37] =       {0xfffffdff, 0xfff7ffff, 0xdfffffff, 0xfffbffff,
                                             0xefffffff, 0xffffffff, 0xfffffeff, 0xfffdffff,
                                             0xf7ffff7f, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xfffeffff, 0xfdffffbf, 0xffff7fff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xfeffffef, 0xffffbfff, 0xff7fffff, 0xffffffff,
                                             0xfffffff7, 0xffffdfff, 0xfffffffb, 0xffffefff,
                                             0xffbfffff, 0x7fffffff, 0xfffffffd, 0xfffff7ff,
                                             0xffdfffff, 0xfffffbff, 0xffefffff, 0xbfffffff,
                                             0xfffffffe};

__device__ const uint32_t p41[41] =       {0xfffffbff, 0xffffffff, 0xffffffff, 0xffdfffff,
                                             0x7ffffdff, 0xffefffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xfff7ffff, 0xbffffeff, 0xfffbffff,
                                             0xffffff7f, 0xffffffff, 0xdfffffff, 0xfffdffff,
                                             0xefffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xf7ffffff, 0xfffeffff, 0xfbffffdf, 0xffff7fff,
                                             0xffffffef, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xfffffff7, 0xffffbfff, 0xfffffffb, 0xffffffff,
                                             0xfeffffff, 0xffffdfff, 0xff7ffffd, 0xffffefff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xfffff7ff,
                                             0xffbffffe};

__device__ const uint32_t p43[43] =       {0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffbfffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffdfffff,
                                             0xffffffff, 0xffefffff, 0x7fffffff, 0xffffffff,
                                             0xfffffeff, 0xfff7ffff, 0xffffff7f, 0xfffbffff,
                                             0xbfffffff, 0xffffffff, 0xffffffff, 0xfffdffff,
                                             0xdfffffbf, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffdf, 0xfffeffff, 0xf7ffffef, 0xffff7fff,
                                             0xfbffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfdfffffb, 0xffffbfff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffdfff, 0xfeffffff, 0xffffefff,
                                             0xff7fffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p47[47] =       {0xffffefff, 0xffffffff, 0xffffffff, 0xfeffffff,
                                             0xfffff7ff, 0xff7fffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffbfffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffdfffff,
                                             0xfffffeff, 0xffefffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xfff7ffff, 0x7fffffff, 0xfffbffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xfffdffff,
                                             0xbfffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xdfffffff, 0xfffeffff, 0xeffffff7, 0xffff7fff,
                                             0xfffffffb, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbfffffd, 0xffffbfff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffdfff, 0xfffffffe};

__device__ const uint32_t p53[53] =       {0xffffbfff, 0xffffffff, 0xffffffff, 0xf7ffffff,
                                             0xffffdfff, 0xfbffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xfdffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xfeffffff,
                                             0xfffffdff, 0xff7fffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffbfffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffdfffff,
                                             0xffffffff, 0xffefffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xfff7ffff, 0xffffffdf, 0xfffbffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xfffdffff,
                                             0x7ffffff7, 0xffffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xfffeffff, 0xbffffffd, 0xffff7fff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xeffffffe};

__device__ const uint32_t p59[59] =       {0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xbfffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xdfffffff, 0xffffdfff, 0xefffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xf7ffffff,
                                             0xfffff7ff, 0xfbffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xfdffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xfeffffff,
                                             0xfffffeff, 0xff7fffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffbfffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffdfffff,
                                             0xffffffdf, 0xffefffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xfff7ffff, 0xfffffff7, 0xfffbffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xfffdffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xfffeffff, 0x7ffffffe};

__device__ const uint32_t p61[61] =       {0xfffeffff, 0xffffffff, 0xffff7fff, 0x7fffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xbfffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xdfffffff, 0xffffefff, 0xefffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xf7ffffff,
                                             0xfffffbff, 0xfbffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xfdffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xfeffffff,
                                             0xffffff7f, 0xff7fffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffbfffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffdfffff,
                                             0xffffffef, 0xffefffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xfff7ffff, 0xfffffffb, 0xfffbffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xfffdffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p67[67] =       {0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0x7fffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xbfffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xdfffffff, 0xfffffbff, 0xefffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xf7ffffff,
                                             0xffffffff, 0xfbffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xfdffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xfeffffff,
                                             0xffffffbf, 0xff7fffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffbfffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffdfffff,
                                             0xfffffffb, 0xffefffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xfff7ffff, 0xffffffff, 0xfffbffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p71[71] =       {0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0x7fffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xbfffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xdfffffff, 0xfffffdff, 0xefffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xf7ffffff,
                                             0xfffffeff, 0xfbffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xfdffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xfeffffff,
                                             0xffffffdf, 0xff7fffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffbfffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffdfffff,
                                             0xfffffffd, 0xffefffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xfff7ffff, 0xfffffffe};

__device__ const uint32_t p73[73] =       {0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0x7fffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xbfffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xdfffffff, 0xffffffff, 0xefffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xf7ffffff,
                                             0xffffff7f, 0xfbffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xfdffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xfeffffff,
                                             0xffffffef, 0xff7fffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0xffbfffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xffdfffff,
                                             0xffffffff, 0xffefffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p79[79] =       {0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0x7fffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xbfffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xdfffffff, 0xffffff7f, 0xefffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xf7ffffff,
                                             0xffffffbf, 0xfbffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xfdffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xfeffffff,
                                             0xfffffffb, 0xff7fffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffbfffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p83[83] =       {0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0x7fffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xbfffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xdfffffff, 0xffffffff, 0xefffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xf7ffffff,
                                             0xffffffdf, 0xfbffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xfdffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xfeffffff,
                                             0xfffffffd, 0xff7fffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p89[89] =       {0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0x7fffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xbfffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xdfffffff, 0xffffffdf, 0xefffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xf7ffffff,
                                             0xfffffff7, 0xfbffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xfdffffff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xfeffffff,
                                             0xfffffffe};

__device__ const uint32_t p97[97] =       {0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0x7fffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xbfffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xdfffffff, 0xfffffffb, 0xefffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xf7ffffff,
                                             0xffffffff, 0xfbffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p101[101] =     {0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0x7fffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xbfffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xdfffffff, 0xfffffffd, 0xefffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xf7ffffff,
                                             0xfffffffe};

__device__ const uint32_t p103[103] =     {0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0x7fffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xbfffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xdfffffff, 0xffffffff, 0xefffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p107[107] =     {0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0x7fffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xbfffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xdfffffff, 0xfffffffe};

__device__ const uint32_t p109[109] =     {0xdfffffff, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0x7fffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xbfffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p113[113] =     {0xbfffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xdfffffff, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0x7fffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p127[127] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0x7fffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xbfffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p131[131] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0x7fffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xbfffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p137[137] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0x7fffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xbfffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xdfffffff, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p139[139] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0x7fffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xbfffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p149[149] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0x7fffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xbfffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xdfffffff, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p151[151] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0x7fffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xbfffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p157[157] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0x7fffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xbfffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xdfffffff, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p163[163] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0x7fffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xbfffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p167[167] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0x7fffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xbfffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p173[173] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0x7fffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xbfffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xdfffffff, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p179[179] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0x7fffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xbfffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p181[181] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0x7fffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xbfffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xdfffffff, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p191[191] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0x7fffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xbfffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

__device__ const uint32_t p193[193] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0x7fffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xbfffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xdfffffff, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p197[197] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0x7fffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xbfffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xdfffffff, 0xffffffff, 0xefffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xf7ffffff, 0xffffffff,
                                             0xfbffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfdffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfeffffff, 0xffffffff,
                                             0xff7fffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffbfffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffdfffff, 0xffffffff,
                                             0xffefffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfff7ffff, 0xffffffff, 0xfffbffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffdffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffeffff, 0xffffffff, 0xffff7fff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffbfff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffdfff, 0xffffffff, 0xffffefff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffff7ff, 0xffffffff,
                                             0xfffffbff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffdff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffeff, 0xffffffff,
                                             0xffffff7f, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffbf, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffdf, 0xffffffff,
                                             0xffffffef, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffff7, 0xffffffff, 0xfffffffb, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffd, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffe};

__device__ const uint32_t p199[199] =     {0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0x7fffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xbfffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xdfffffff, 0xffffffff,
                                             0xefffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xf7ffffff, 0xffffffff, 0xfbffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfdffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfeffffff, 0xffffffff, 0xff7fffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffbfffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffdfffff, 0xffffffff, 0xffefffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfff7ffff, 0xffffffff,
                                             0xfffbffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffdffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffeffff, 0xffffffff,
                                             0xffff7fff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffbfff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffdfff, 0xffffffff,
                                             0xffffefff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffff7ff, 0xffffffff, 0xfffffbff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffdff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffeff, 0xffffffff, 0xffffff7f, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffbf, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffdf, 0xffffffff, 0xffffffef, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffff7, 0xffffffff,
                                             0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xfffffffd, 0xffffffff, 0xffffffff, 0xffffffff,
                                             0xffffffff, 0xffffffff, 0xfffffffe};

       
		
	}
}

#endif